In [1]:
from google.colab import drive 
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/T2D-ML/T2D-Level-Final_GSE81608_GeneLevel_Raw_data.csv')
df.head()

,Sample_Names,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,...,MIR3913-2,MIR6830,TCF20.7,MIR548AH,MIR522,MIR6715B,MIR3116-2,MIR3202-2,HSFX3,MIR4481
0,GSM2157899,4.0685,0.0,0.0000,6.0980,0.0000,0.0,0.0000,8.6118,0.0000,...,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,GSM2157900,0.8755,0.0,6.2501,10.3465,0.0000,0.0,0.0000,16.2721,85.7705,...,0.0,0.0,0.8168,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,GSM2157901,1.2943,0.0,62.6107,12.2002,1.8483,0.0,7.4244,4.1191,1.6251,...,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,GSM2157902,0.0000,0.0,0.0000,22.1665,0.0000,0.0,0.0000,0.0000,0.7967,...,0.0,0.0,10.8795,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,GSM2157903,11.4406,0.0,18.2915,6.2444,0.0000,0.0,0.0000,3.4575,0.0000,...,0.0,0.0,5.5639,0.0,0.0,0.0,0.0,0.0,0.0,0.0

###**Import Meta-Data**

In [ ]:
import pandas as pd
md = pd.read_csv('/content/drive/MyDrive/T2D-ML/T2D_Meta_GSE81608_filtered_metadata.csv')

In [ ]:
md.head()

,Unnamed: 0,characteristics,condition,age,ethnicity,gender,cell subtype
0,GSM2157899,Pancreatic islet cell sample 1,non-diabetic,23,AA,M,beta
1,GSM2157900,Pancreatic islet cell sample 2,non-diabetic,23,AA,M,beta
2,GSM2157901,Pancreatic islet cell sample 3,non-diabetic,23,AA,M,beta
3,GSM2157902,Pancreatic islet cell sample 4,non-diabetic,23,AA,M,beta
4,GSM2157903,Pancreatic islet cell sample 5,non-diabetic,23,AA,M,beta

In [ ]:
md.rename( columns={'Unnamed: 0':'Sample_Names'}, inplace=True )

In [ ]:
md.head()

,Sample_Names,characteristics,condition,age,ethnicity,gender,cell subtype
0,GSM2157899,Pancreatic islet cell sample 1,non-diabetic,23,AA,M,beta
1,GSM2157900,Pancreatic islet cell sample 2,non-diabetic,23,AA,M,beta
2,GSM2157901,Pancreatic islet cell sample 3,non-diabetic,23,AA,M,beta
3,GSM2157902,Pancreatic islet cell sample 4,non-diabetic,23,AA,M,beta
4,GSM2157903,Pancreatic islet cell sample 5,non-diabetic,23,AA,M,beta

In [ ]:
md['condition'].unique()

array(['non-diabetic', 'T2D'], dtype=object)

In [ ]:
type(md['condition'][1])

str

In [ ]:
print(df.shape)
print(md.shape)

(1600, 28090)
(1600, 7)

In [ ]:
###Merge RawData and Metadata
dfm = pd.merge(df, md[["Sample_Names", "condition"]], on="Sample_Names", how="left")

In [ ]:
dfm.head()

,Sample_Names,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,...,MIR6830,TCF20.7,MIR548AH,MIR522,MIR6715B,MIR3116-2,MIR3202-2,HSFX3,MIR4481,condition
0,GSM2157899,4.0685,0.0,0.0000,6.0980,0.0000,0.0,0.0000,8.6118,0.0000,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,non-diabetic
1,GSM2157900,0.8755,0.0,6.2501,10.3465,0.0000,0.0,0.0000,16.2721,85.7705,...,0.0,0.8168,0.0,0.0,0.0,0.0,0.0,0.0,0.0,non-diabetic
2,GSM2157901,1.2943,0.0,62.6107,12.2002,1.8483,0.0,7.4244,4.1191,1.6251,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,non-diabetic
3,GSM2157902,0.0000,0.0,0.0000,22.1665,0.0000,0.0,0.0000,0.0000,0.7967,...,0.0,10.8795,0.0,0.0,0.0,0.0,0.0,0.0,0.0,non-diabetic
4,GSM2157903,11.4406,0.0,18.2915,6.2444,0.0000,0.0,0.0000,3.4575,0.0000,...,0.0,5.5639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,non-diabetic

In [2]:
dfm.to_csv('/content/drive/MyDrive/T2D-ML/T2D_Meta_GSE81608_filtered_metadata.csv', index = False)

dfm.head()

NameError: ignored

In [ ]:
dfm['condition'].unique()

array(['non-diabetic', 'T2D'], dtype=object)

In [ ]:
dfm_2 = dfm.copy()

In [ ]:
dfm_2.loc[dfm_2['condition'] == 'T2D', 'condition'] = 1

In [ ]:
dfm_2.loc[dfm_2['condition'] == 'non-diabetic', 'condition'] = 0

In [ ]:
dfm_2.head()

,Sample_Names,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,...,MIR6830,TCF20.7,MIR548AH,MIR522,MIR6715B,MIR3116-2,MIR3202-2,HSFX3,MIR4481,condition
0,GSM2157899,4.0685,0.0,0.0000,6.0980,0.0000,0.0,0.0000,8.6118,0.0000,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,GSM2157900,0.8755,0.0,6.2501,10.3465,0.0000,0.0,0.0000,16.2721,85.7705,...,0.0,0.8168,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,GSM2157901,1.2943,0.0,62.6107,12.2002,1.8483,0.0,7.4244,4.1191,1.6251,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,GSM2157902,0.0000,0.0,0.0000,22.1665,0.0000,0.0,0.0000,0.0000,0.7967,...,0.0,10.8795,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,GSM2157903,11.4406,0.0,18.2915,6.2444,0.0000,0.0,0.0000,3.4575,0.0000,...,0.0,5.5639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [ ]:
dfm_2['condition'].unique()

array([0, 1], dtype=object)

In [ ]:
dfm_2['condition'].count()

1600

In [ ]:
dfm_2.to_csv('/content/drive/MyDrive/T2D-ML/Final_T2D_Meta_GSE81608_filtered_metadata.csv', index = False)

###Import the final CSV-file

In [3]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/T2D-ML/Datasets/Final_T2D_Meta_GSE81608_filtered_metadata.csv')

df.head()

,Sample_Names,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,...,MIR6830,TCF20.7,MIR548AH,MIR522,MIR6715B,MIR3116-2,MIR3202-2,HSFX3,MIR4481,condition
0,GSM2157899,4.0685,0.0,0.0000,6.0980,0.0000,0.0,0.0000,8.6118,0.0000,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,GSM2157900,0.8755,0.0,6.2501,10.3465,0.0000,0.0,0.0000,16.2721,85.7705,...,0.0,0.8168,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,GSM2157901,1.2943,0.0,62.6107,12.2002,1.8483,0.0,7.4244,4.1191,1.6251,...,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,GSM2157902,0.0000,0.0,0.0000,22.1665,0.0000,0.0,0.0000,0.0000,0.7967,...,0.0,10.8795,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,GSM2157903,11.4406,0.0,18.2915,6.2444,0.0000,0.0,0.0000,3.4575,0.0000,...,0.0,5.5639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [4]:
df['condition'].value_counts()

1    949
0    651
Name: condition, dtype: int64

In [5]:
949+651

1600